### ISSUE TITLE
Please add license

### ISSUE THREAD

**Issue by mytja** [Mankifg/DiscordBot#54]
It's not in the true open-source spirit to not add a license. Please consider MIT or GPL.

**Comment by mytja** [comment]
I wanna use this project so bad :sob::sob::sob::sob::sob::sob::sob::sob::sob::sob::sob::sob::sob::sob::sob::sob::sob::sob::sob::sob::sob::sob::sob:

**Comment by Mankifg** [comment]
added license, thanks for reminding me

**Comment by mytja** [comment]
Thank you 🥳🥳🥰🥰🥰
