### ISSUE TITLE
Rad bi prijavil napako

### ISSUE THREAD

**Issue by Mato2007** [Mankifg/DiscordBot#55]
Poslal sem ti PR(v Readme.MD si navedel da  so dobrodosli). PR si zavrnil in napako popravil sam. Upam da se zavedas tega, da to ni bilo lepo.  Glede na to kaj si storil, predvidevam da si mentalno star 5 let.
LP od osebe ki popravlja tvojo slovnico:D
![Mv976fY6pMCn](https://user-images.githubusercontent.com/88381738/184924773-93fa63b8-0823-46fb-a1cf-c4a0a49b3f76.jpg)

**Comment by mytja** [comment]
To ni v open source spiritu. Avtor zelo očitno nima respecta za odprtokoden community. Upam, da si bo avtor premislil...
